-- 조인 연습문제
-- 1) = 조인을 이용해서 SCOTT 사원의 부서번호와 부서이름을 출력하시오.
SELECT
    EMPLOYEE.ENAME,
    DEPARTMENT.DNO,
    DEPARTMENT.DNAME
FROM
    DEPARTMENT,
    EMPLOYEE
WHERE
    DEPARTMENT.DNO = EMPLOYEE.DNO
    AND ENAME = 'SCOTT'
ORDER BY
    EMPLOYEE.ENAME;

-- 2) 모든 사원의 사원이름과 그 사원이 소속된 부서이름과 지역명을 출력하시오.
SELECT
    EMPLOYEE.ENAME,
    DEPARTMENT.DNAME,
    DEPARTMENT.LOC
FROM
    DEPARTMENT,
    EMPLOYEE
WHERE
    DEPARTMENT.DNO = EMPLOYEE.DNO
ORDER BY
    EMPLOYEE.ENAME;

-- 3) 10번 부서에 속하는 사원에 대해 직급과 지역명을 출력하시오.
SELECT
    EMPLOYEE.ENAME,
    EMPLOYEE.JOB,
    DEPARTMENT.DNAME,
    DEPARTMENT.LOC
FROM
    DEPARTMENT,
    EMPLOYEE
WHERE
    DEPARTMENT.DNO = EMPLOYEE.DNO
    AND EMPLOYEE.DNO = 10
ORDER BY
    EMPLOYEE.ENAME;

-- 4) 커미션을 받는 모든사원의 이름, 부서이름, 지역명을 출력하시오.
SELECT
    EMPLOYEE.ENAME,
    EMPLOYEE.COMMISSION,
    DEPARTMENT.DNAME,
    DEPARTMENT.LOC
FROM
    DEPARTMENT,
    EMPLOYEE
WHERE
    DEPARTMENT.DNO = EMPLOYEE.DNO
    AND EMPLOYEE.COMMISSION IS NOT NULL
ORDER BY
    EMPLOYEE.ENAME;

-- 5) = 조인과 와일드카드(%)를 사용하여 이름에 A가 포함된 모든 사원의 이름과 부서명을 출력하시오.
SELECT
    EMPLOYEE.ENAME,
    DEPARTMENT.DNAME
FROM
    DEPARTMENT,
    EMPLOYEE
WHERE
    DEPARTMENT.DNO = EMPLOYEE.DNO
    AND EMPLOYEE.ENAME LIKE '%A%'
ORDER BY
    EMPLOYEE.ENAME;

-- 6) NEW YORK 에 근무하는 모든 사원의 이름, 업무, 부서번호 및 부서명을 출력하시오.
SELECT
    EMPLOYEE.ENAME,
    EMPLOYEE.JOB,
    EMPLOYEE.DNO,
    DEPARTMENT.DNAME,
    DEPARTMENT.LOC
FROM
    DEPARTMENT,
    EMPLOYEE
WHERE
    DEPARTMENT.DNO = EMPLOYEE.DNO
    AND DEPARTMENT.LOC = 'NEW YORK'
ORDER BY
    EMPLOYEE.ENAME;