-- TODO: 데이터 무결성과 제약조건
-- 무결성: 기본키, 외래키
-- 제약조건: NOT NULL, UNIQUE, CHECK

-- TODO: NOT NULL 제약조건: 컬럼에 데이터가 NULL값이 INSERT 되지 못하게 막는 조건.
-- 기본키, 외래키인 컬럼 및 필요한 곳에 사용.
CREATE TABLE CUSTOMER(
    ID VARCHAR2(20) NOT NULL,
    PWD VARCHAR2(20) NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    PHONE VARCHAR2(30),
    ADDRESS VARCHAR2(1000)
);

DROP TABLE CUSTOMER;

-- TODO: UNIQUE 제약조건: 유일한 값만 허용됨(중복된 값은 들어올수 없음.).
CREATE TABLE CUSTOMER(
    ID VARCHAR2(20) UNIQUE,
    PWD VARCHAR2(20) NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    PHONE VARCHAR2(30),
    ADDRESS VARCHAR2(1000)
);

DROP TABLE CUSTOMER;

-- TODO: 기본키(PRIMARY KEY) 제약조건: NOT NULL + UNIQUE 기능을 가짐.
CREATE TABLE CUSTOMER(
    ID VARCHAR2(20),
    PWD VARCHAR2(20) CONSTRAINT CUSTOMER_PWD_NN NOT NULL,
    NAME VARCHAR(20) CONSTRAINT CUSTOMER_NAME_NN NOT NULL,
    PHONE VARCHAR2(30),
    ADDRESS VARCHAR2(1000),
    CONSTRAINT CUSTOMER_ID_PK PRIMARY KEY(ID)
);

-- 기본키 및 제약조건에 의해 NULL 값은 들어갈 수가 없음.
INSERT INTO CUSTOMER VALUES (
    NULL,
    NULL,
    NULL,
    '010-1111-1111',
    'SEOUL'
);

-- TODO: 외래키(FOREIGN KEY) 제약조건: 연결되는 테이블간의 관계 (참조 무결성)
CREATE TABLE EMP_SECOND (
    ENO NUMBER(4) CONSTRAINT EMP_SECOND_ENO_PK PRIMARY KEY,
    ENAME VARCHAR2(10),
    JOB VARCHAR2(9),
    DNO NUMBER(2) CONSTRAINT EMP_SECOND_ENO_FK REFERENCES DEPARTMENT
);

DROP TABLE EMP_SECOND;

-- TODO: CHECk 제약조건: 컬럼에서 허용 가능한 데이터의 범위나 조건을 정의할 수 있음.
-- SALARY에 0보다 큰값만 들어올 수 있도록 제약조건을 만들수 있음.
CREATE TABLE EMP_SECOND (
    ENO NUMBER(4) CONSTRAINT EMP_SECOND_ENO_PK PRIMARY KEY,
    ENAME VARCHAR2(10),
    SALARY NUMBER(7, 2) CONSTRAINT EMP_SECOND_SALARY_CK CHECK(SALARY > 0)
);

DROP TABLE EMP_SECOND;

INSERT INTO EMP_SECOND VALUES (
    8000,
    '류종학',
    -200
);

-- TODO: DEFAULT 제약조건: 사용 시 NULL 값 대신 DEFAULT로 설정된 값이 들어간다.
CREATE TABLE EMP_SECOND (
    ENO NUMBER(4) CONSTRAINT EMP_SECOND_ENO_PK PRIMARY KEY,
    ENAME VARCHAR2(10),
    SALARY NUMBER(7, 2) DEFAULT 1000
);

DROP TABLE EMP_SECOND;

INSERT INTO EMP_SECOND(
    ENO,
    ENAME
) VALUES (
    8000,
    '류종학'
);

SELECT
    *
FROM
    EMP_SECOND;

-- TODO: 제약조건 변경하기
-- 테이블 생성후에 제약조건 걸기
DROP TABLE EMP_COPY;

-- TABLE COPY 단점: 제약조건 누락
CREATE TABLE EMP_COPY AS
    SELECT
        *
    FROM
        EMPLOYEE;

DROP TABLE DEPT_COPY;

-- TABLE COPY 단점: 제약조건 누락
CREATE TABLE DEPT_COPY AS
    SELECT
        *
    FROM
        DEPARTMENT;

-- 원본 제약조건 조회하기
SELECT
    TABLE_NAME,
    CONSTRAINT_NAME
FROM
    USER_CONSTRAINTS
WHERE
    TABLE_NAME IN('EMPLOYEE',
    'DEPARTMENT');

-- 복사본 제약조건 조회하기
SELECT
    TABLE_NAME,
    CONSTRAINT_NAME
FROM
    USER_CONSTRAINTS
WHERE
    TABLE_NAME IN('EMP_COPY',
    'DEPT_COPY');

-- TODO: 기본키 제약조건 추가하기
ALTER TABLE EMP_COPY ADD CONSTRAINT EMP_COPY_ENO_PK PRIMARY KEY(ENO);

ALTER TABLE DEPT_COPY ADD CONSTRAINT DEPT_COPY_DNO_PK PRIMARY KEY(DNO);

-- TODO: 외래키 제약조건 추가하기
ALTER TABLE EMP_COPY ADD CONSTRAINT EMP_COPY_ENO_FK FOREIGN KEY(DNO) REFERENCES DEPT_COPY;

-- TODO: NOT NULL 제약조건 변경하기(NULL ->  NOT NULL)
ALTER TABLE EMP_COPY MODIFY ENAME CONSTRAINT EMP_COPY_ENAME_NN NOT NULL;

-- TODO: 제약조건 제거하기(CASCADE(외래키를 제거) 옵션을 사용하여 강제 제거 가능.)
ALTER TABLE DEPT_COPY DROP PRIMARY KEY CASCADE;

-- TODO: 제약조건 이름으로 삭제 가능.
ALTER TABLE EMP_COPY DROP CONSTRAINT EMP_COPY_ENO_PK;

-- TODO: NOT NULL 제약조건 삭제(제약조건 이름으로 삭제 가능.)
ALTER TABLE EMP_COPY DROP CONSTRAINT EMP_COPY_ENAME_NN;