-- 연습문제: DDL (CREATE / 컬럼추가 / 삭제 / 변경)
-- 연습문제: DEPT 테이블을 생성하세요. 단, DEPT 테이블이 있으면 삭제하고 재생성하세요.
-- 컬럼명: DNO NUMBER(2), DNAME VARCHAR2(14), LOC VARCHAR2(13)
CREATE TABLE DEPT(
    DNO NUMBER(2),
    DNAME VARCHAR2(14),
    LOC VARCHAR2(13)
);

-- 2) EMP 테이블을 생성하세요.
-- 단, EMP 테이블이 있으면 삭제하고 재생성하세요.
-- 컬럼명 : ENO NUMBER(4), ENAME VARCHAR2(10), DNO NUMBER(2)
CREATE TABLE EMP(
    ENO NUMBER(4),
    ENAME VARCHAR2(10),
    DNO NUMBER(2)
);

-- 3) EMP 테이블을 수정하세요.(ENAME 컬럼 크기)
-- 컬럼명 : ENO   NUMBER(4)
--         ENAME VARCHAR2(25)
--         DNO   NUMBER(2)
ALTER TABLE EMP MODIFY ENAME VARCHAR2(25);

-- 4) EMPLOYYE 테이블을 복사해서 EMPLOYEE2 테이블을 생성하되
--    사원번호(ENO), 이름(ENAME), 급여(SALARY), 부서번호(DNO) 컬럼만 복사하고,
--    새로 생성된 테이블의 컬럼명은 각각 EMP_ID, NAME, SAL, DEPT_ID로 지정하세요.
-- 방법 1)
CREATE TABLE EMPLOYEE2(
    EMP_ID,
    NAME,
    SAL,
    DEPT_ID
) AS
    SELECT
        ENO,
        ENAME,
        SALARY,
        DNO
    FROM
        EMPLOYEE;

-- 방법 2)
CREATE TABLE EMPLOYEE2 AS
    SELECT
        *
    FROM
        EMPLOYEE;

ALTER TABLE EMPLOYEE2 DROP COLUMN JOB;

ALTER TABLE EMPLOYEE2 DROP COLUMN MANAGER;

ALTER TABLE EMPLOYEE2 DROP COLUMN HIREDATE;

ALTER TABLE EMPLOYEE2 DROP COLUMN COMMISSION;

ALTER TABLE EMPLOYEE2 RENAME COLUMN ENO TO EMP_ID;

ALTER TABLE EMPLOYEE2 RENAME COLUMN ENAME TO NAME;

ALTER TABLE EMPLOYEE2 RENAME COLUMN SALARY TO SAL;

ALTER TABLE EMPLOYEE2 RENAME COLUMN DNO TO DEPT_ID;

-- 5) EMP 테이블을 삭제하세요.
DROP TABLE EMP;

-- 6) EMPLOYEE2란 이름을 EMP로 변경하세요.
RENAME EMPLOYEE2 TO EMP;

-- 7) DEPT 테이블에서 DNAME 컬럼을 제거하세요.
ALTER TABLE DEPT DROP COLUMN DNAME;