-- TODO: 1번 문제
-- 계정생성
CREATE USER GUEST03 IDENTIFIED BY 1234;

-- 권한 부여
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO USERTEST01;

-- 저장소 부여
ALTER USER GUEST03 DEFAULT TABLESPACE USERS;

-- 임시저장소 부여
ALTER USER GUEST03 TEMPORARY TABLESPACE TEMP;

-- 계정 삭제
DROP USER GUEST03 CASCADE;

-- TODO: 2번문제
CREATE TABLE DEPT03(
    DEPTNO VARCHAR2(3),
    DNAME VARCHAR2(7)
);

COMMENT ON TABLE DEPT03 IS '부서정보';
COMMENT ON COLUMN DEPT03.DEPTNO IS '부서번호';
COMMENT ON COLUMN DEPT03.DNAME IS '부서명';

SELECT
    *
FROM
    DEPT03;

-- TODO: 3번 문제
ALTER TABLE DEPT03 ADD (AREA VARCHAR2(20));

-- TODO: 4번 문제
ALTER TABLE DEPT03 MODIFY DNAME VARCHAR2(20);

-- TODO: 5번 문제
ALTER TABLE DEPT03 ADD CONSTRAINT PK_DEPTNO PRIMARY KEY(DEPTNO);

-- TODO: 6번 문제
ALTER TABLE DEPT03 MODIFY DNAME CONSTRAINT NN_DEPTNO NOT NULL;

ALTER TABLE DEPT03 MODIFY CONSTRAINT UK_DEPTNO UNIQUE DNAME;

CREATE INDEX UK_DEPTNO ON DEPT03(
    DNAME
);

-- TODO:  7번 문제
CREATE TABLE EMP03(
    EMPNO VARCHAR2(4) CONSTRAINT PK_EMPNO PRIMARY KEY,
    NAME VARCHAR2(20),
    DEPTNO VARCHAR2(3) NOT NULL,
    PEMPNO VARCHAR2(4),
    PAY NUMBER NOT NULL,
    POSITION VARCHAR2(20),
    REGDATE VARCHAR2(20)
);

COMMENT ON TABLE EMP03 IS '사원';
COMMENT ON COLUMN EMP03.EMPNO IS '사원코드';
COMMENT ON COLUMN EMP03.NAME IS '사원이름';
COMMENT ON COLUMN EMP03.DEPTNO IS '부서코드';
COMMENT ON COLUMN EMP03.PEMPNO IS '상사코드';
COMMENT ON COLUMN EMP03.PAY IS '급여';
COMMENT ON COLUMN EMP03.POSITION IS '직급';
COMMENT ON COLUMN EMP03.REGDATE IS '등록일';


-- TODO:  8번 문제
ALTER TABLE EMP03 ADD CONSTRAINT FK_EMP03_DEPT03 FOREIGN KEY(DEPTNO) REFERENCES DEPT03;

-- TODO:  9번 문제
CREATE SEQUENCE SEQ_EMP03_EMPNO INCREMENT BY 1 START WITH 1000;

-- SEQUENCE 확인
SELECT
    SEQUENCE_NAME,
    MIN_VALUE,
    MAX_VALUE,
    INCREMENT_BY
FROM
    USER_SEQUENCES;

-- TODO:  10번 문제
-- DEPT03 데이터 추가
INSERT INTO DEPT03 VALUES (
    101,
    '영업부',
    NULL
);

INSERT INTO DEPT03 VALUES (
    102,
    '총무부',
    NULL
);

INSERT INTO DEPT03 VALUES (
    103,
    '기획부',
    NULL
);

INSERT INTO DEPT03 VALUES (
    104,
    '홍보부',
    NULL
);

-- EMP03 데이터추가
INSERT INTO EMP03 VALUES (
    SEQ_EMP03_EMPNO.NEXTVAL,
    '가가가',
    101,
    NULL,
    450,
    '부장',
    NULL
);

INSERT INTO EMP03 VALUES (
    SEQ_EMP03_EMPNO.NEXTVAL,
    '나나나',
    102,
    NULL,
    400,
    '부장',
    NULL
);

INSERT INTO EMP03 VALUES (
    SEQ_EMP03_EMPNO.NEXTVAL,
    '다다다',
    101,
    1001,
    350,
    '과장',
    NULL
);

INSERT INTO EMP03 VALUES (
    SEQ_EMP03_EMPNO.NEXTVAL,
    '라라라',
    103,
    NULL,
    410,
    '과장',
    NULL
);

INSERT INTO EMP03 VALUES (
    SEQ_EMP03_EMPNO.NEXTVAL,
    '마마마',
    101,
    1003,
    300,
    '대리',
    NULL
);

INSERT INTO EMP03 VALUES (
    SEQ_EMP03_EMPNO.NEXTVAL,
    '바바바',
    103,
    1004,
    400,
    '대리',
    NULL
);

INSERT INTO EMP03 VALUES (
    SEQ_EMP03_EMPNO.NEXTVAL,
    '가나다',
    102,
    1002,
    320,
    '대리',
    NULL
);

INSERT INTO EMP03 VALUES (
    SEQ_EMP03_EMPNO.NEXTVAL,
    '홍길동',
    102,
    1007,
    380,
    '사원',
    NULL
);

INSERT INTO EMP03 VALUES (
    SEQ_EMP03_EMPNO.NEXTVAL,
    '강감찬',
    103,
    1006,
    250,
    '사원',
    NULL
);

INSERT INTO EMP03 VALUES (
    SEQ_EMP03_EMPNO.NEXTVAL,
    '이순신',
    101,
    1005,
    200,
    '사원',
    NULL
);

-- EMP03 데이터 확인
SELECT
    *
FROM
    EMP03;

-- TODO:  11번 문제
UPDATE DEPT03
SET
    AREA = '부산';

UPDATE DEPT03
SET
    AREA = '서울'
WHERE
    DNAME = '영업부';

COMMIT;

-- TODO:  12번 문제
DELETE FROM EMP03
WHERE
    DEPTNO = 101;

ROLLBACK;

-- TODO: 13번 문제
SELECT
    NAME,
    POSITION
FROM
    EMP03
WHERE
    DEPTNO IN (
        SELECT
            DEPTNO
        FROM
            DEPT03
        WHERE
            DNAME IN ('영업부',
            '총무부')
    )
ORDER BY
    EMPNO;

-- TODO: 14번 문제
SELECT
    EMPNO,
    NAME
FROM
    EMP03;

-- TODO: 15번 문제
SELECT
    NAME,
    PAY,
    CASE
        WHEN 300 < PAY AND PAY <= 400 THEN
            PAY + ((PAY/100) *15)
        WHEN 200 < PAY AND PAY <= 300 THEN
            PAY + ((PAY/100) *10)
        WHEN 0 < PAY AND PAY <= 200 THEN
            PAY + ((PAY/100) *5)
        ELSE
            PAY + ((PAY/100) *20)
    END AS TAX
FROM
    EMP03;

-- TODO: 16번 문제
SELECT
    DEPTNO,
    TRUNC(AVG(PAY)),
    COUNT(DEPTNO)
FROM
    EMP03
GROUP BY
    DEPTNO;

-- TODO: 17번 문제
SELECT
    EMP03.DEPTNO,
    DEPT03.DNAME,
    AVG(PAY)
FROM
    EMP03,
    DEPT03
WHERE
    EMP03.DEPTNO = DEPT03.DEPTNO
HAVING
    AVG(PAY) > 350
GROUP BY
    DEPTNO;

-- TODO: 18번 문제
CREATE INDEX IDX_EMP03 ON EMP03(
    NAME
);

COMMIT;