-- TODO: ROLE(권한): 권한들의 모임.
-- TODO: CREATE USER 계정명 IDENTIFIED BY 패스워드; : USER(사용자) 만들기.
CREATE USER USERTEST01 IDENTIFIED BY PASS1;

-- TODO:  GRANT 권한명 TO 계정명;
--  CREATE SESSION 권한 생성(SQL DEV 접속).
GRANT CREATE SESSION TO USERTEST01;

-- CREATE TABLE 권한 생성
GRANT CREATE TABLE TO USERTEST01;

-- CREATE SYNONYM 권한 생성
GRANT CREATE SYNONYM TO USERTEST01;

-- TODO: 권한(GRANT) : 접속, 리소드 사용권한 줘야됨
-- TODO: 권한 종류 : CONNECT(접속), RESOURCE(테이블, 인덱스, 함수, 프로시저, 시퀀스 등), UNLIMITED TABLESPACE(물리적인 공간(테이블이 저장된 공간))
-- TODO: DBA(관리자 권한)
GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO USERTEST01;

-- SQL 문법 : ALTER USER 계정명 DEFAULT TABLESPACE 전용공간명(USERS);
-- 공간: SYSTEM -> USERS
ALTER USER USERTEST01 DEFAULT TABLESPACE USERS;

-- ALTER USER 계정명 TEMPORARY TABLESPACE 임시공간(TEMP);
ALTER USER USERTEST01 TEMPORARY TABLESPACE TEMP;

-- 수정 ALTER
ALTER USER PASS1 IDENTIFIED BY PASS1;

-- 패스워드 락 풀기
ALTER USER USERTEST01 ACCOUNT UNLOCK;

-- SELECT 권한: GRANT SELECT ON 테이블명 TO 계정명;(시스템에 있는 테이블을 볼 수 있다.)

-- TODO: REVOKE 권한명 FROM 계정명; : 권한 회수.
REVOKE CREATE SESSION FROM USERTEST01;